name: task_sheduler
description: A new Flutter project.

publish_to: 'none' 

version: 1.5.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^ 7.3.0
  equatable: ^ 1.0.0
  sqflite: ^ 1.3.0
  path_provider: ^ 1.6.24
  percent_indicator: ^2.1.9

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true